# -*- coding: utf-8 -*-
"""NbaDataManipulation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yoOuUCc9ZJDKTXmnH-6S3YaqJGq8CHve
"""

import pandas as pd
from google.colab import files
uploaded = files.upload()

files.download("all_seasons.csv")

for fn in uploaded.keys():
  print('Arquivo "{name}" com o tamanho de {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

nba_seasons =  pd.read_csv("all_seasons.csv")

nba_seasons.shape

#MOSTRANDO OS 10 PRIMEIROS
nba_seasons.head(10)

nba_seasons.describe()

#JOGADORES MAIS ALTOS
print("JOGADORES MAIS ALTOS DA NBA")
nba_seasons.sort_values(by=['player_height'], ascending=False).drop_duplicates(subset=['player_name']).head(5)

#JOGADORES MAIS ALTOS
print("JOGADORES MAIS PONTOS DA NBA")
nba_seasons.sort_values(by=['pts'], ascending=False).drop_duplicates(subset=['player_name']).head(5)

print("Jogadores do houston rockets com mais pontos")
houston_data = nba_seasons[nba_seasons.team_abbreviation == "HOU"]
houston_data.sort_values(by=["pts"], ascending=False).drop_duplicates(subset=['player_name']).head(5)

print("Todos os jogadores")
nba_seasons.drop_duplicates(subset=['player_name'])["player_name"]

print("Jogadores da nba com mais assistencias")
nba_seasons.sort_values(by=["ast"], ascending=False).drop_duplicates(subset=['player_name']).head(5)

print("Jogadores da nba com mais rebotes")
nba_seasons.sort_values(by=["reb"], ascending=False).drop_duplicates(subset=['player_name']).head(5)

print("Jogadores com maiores pontos na temporada de 2019/20")
nba_season_2019 = nba_seasons[nba_seasons.season == "2019-20"]
nba_season_2019.sort_values(by=["pts"], ascending=False).drop_duplicates(subset=['player_name']).head(5)